# Generated by Django 5.0.2 on 2024-02-10 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+996 XXX XXX XXX'.", regex='^\\+996 \\d{3} \\d{3} \\d{3}$')]),
        ),
    ]
