# Generated by Django 5.0.2 on 2024-02-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_project_author_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
    ]
